server:
  port: 9010
spring:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
services:
  auth:
    url: http://localhost:9010 # 인증 서비스 URL
  member:
    url: http://localhost:9020  # 회원 서비스 URL