server:
  port: 9010
spring:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        default_batch_fetch_size: 100
  kafka:
    #    bootstrap-servers: 210.113.34.187:19092,210.113.34.187:29092,210.113.34.187:39092
    bootstrap-servers: host.docker.internal:19092
#    bootstrap-servers: localhost:19092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#services:
#  auth:
#    url: http://host.docker.internal:9010 # 인증 서비스 URL
#  member:
#    url: http://host.docker.internal:9020  # 회원 서비스 URL
services:
  auth:
    url: http://localhost:9010 # 인증 서비스 URL
  member:
    url: http://localhost:9020  # 회원 서비스 URL

# application-test.yml (테스트 환경)
auth:
  test-mode: true
  refresh-token:
    rotate: false  # 테스트시에만 갱신 안함