server:
  port: 9010
spring:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        default_batch_fetch_size: 100
  kafka:
    bootstrap-servers: 172.30.1.23:19092,172.30.1.23:29092,172.30.1.23:39092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
services:
  auth:
    url: http://172.30.1.23:9010 # 인증 서비스 URL
  member:
    url: http://172.30.1.23:9020  # 회원 서비스 URL
custom:
  prod:
    cookieDomain: chibbotec.kknaks.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "chibbotech"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"

# application-prod.yml (운영 환경)
auth:
  test-mode: false
  refresh-token:
    rotate: true   # 운영에서는 반드시 갱신